### ISSUE TITLE
Could I rebuild resource to .moc format

### ISSUE THREAD

**Issue by xqymain** [ihopenot/LpkUnpacker#1]
Thanks to your LpkUnpacker tool, I have unpacked it and got skeleton, model and textures.
But it's still difficult to me to convert it.

**Comment by ihopenot** [comment]
啥意思，模型不就是.moc文件吗，你是想转成cubism的工程文件吗

**Comment by mijuku233** [comment]
非常感谢大佬制作的工具，我在使用时碰到一点问题。
一个30m的lpk文件解密出来只有18m，缺失了近一半数据，是怎么回事？

我输入的命令：
python LpkUnpacker.py -c .\L2dFile\config.json .\L2dFile\2841455416.lpk .\Export
