### ISSUE TITLE
一点小缺陷

### ISSUE THREAD

**Issue by muyi5201314** [ihopenot/LpkUnpacker#13]
感谢分享，我在使用该代码解包时发现许多解不出来，看了看代码，发现live2dView的命令有两种命名格式，一种是_Command结尾，还有一种时_PostCommand，需要在这里加一个or
![image](https://github.com/ihopenot/LpkUnpacker/assets/94849300/ea9c9843-abab-40b3-94ce-be978402e885)

**Comment by ihopenot** [comment]
非常感谢。如果你有一个成熟的修复方案，欢迎你直接提交一个pull request

**Comment by muyi5201314** [comment]
同时，存在lpk太大，导致递归层数太多而导致代码崩溃，可能是我太贪心了。因为我日常编程并不怎么使用python，而是node.js和java。修改源代码的话，我可能会建立一个Map("dasdsad.bin3", 文件名)。等待所有文件处理完之后再扫描model3.json文件。实际上这种大文件的需求很少，不改的话，影响并不是太大，这里只是分享一下。
![image](https://github.com/ihopenot/LpkUnpacker/assets/94849300/c9169ed0-e7d1-4598-8575-a484558c687d)

**Comment by ihopenot** [comment]
python默认递归深度好像是1000，正常使用一般来说是不会爆的。之前修了一个extract loop导致的深度爆炸的错误，你本地的版本是不是还没有更新？如果确认有这样的问题可以把lpk发一份我看看什么情况（

**Comment by muyi5201314** [comment]
你好，我是10月份下载的代码，我解包的创意工坊里面的灵魂潮汐合集。我看了看，人物应该是120个左右，然后我把lpk文件搞到了网盘，大小为3.7个G，网址为https://www.123pan.com/s/617njv-Mlhtv.html。需要把前面的or加上，然后config的网址为https://www.123pan.com/s/617njv-Ilhtv.html。我这边打算加一个数组和Map表，实际上要实现深度优先遍历改为广度优先遍历，代码并不复杂，但是只是简单的实现功能的话，会破坏代码结构，不美观罢了。

**Comment by ihopenot** [comment]
我这边测试是没有问题的，解出来4.6个G应该是没缺数据
![image](https://github.com/ihopenot/LpkUnpacker/assets/22445677/45d861be-a24b-4720-8583-d2a00a2c2b6d)
