### ISSUE TITLE
支持较早的lpk格式

### ISSUE THREAD

**Issue by ECCQ700** [ihopenot/LpkUnpacker#18]
如题，目前手上有一个疑似较早版本格式的lpk，Live2DViewerEX可以加载，但是用此工具无法解包
![image](https://github.com/user-attachments/assets/461076ad-9f42-4ad7-a891-d3aa5034416d)

下面是含lpk文件的压缩包

[lpk.zip](https://github.com/user-attachments/files/16639815/lpk.zip)

**Comment by ihopenot** [comment]
这都没加密的，直接把lpk后缀名改成zip解压就完事了

**Comment by ihopenot** [comment]
好吧确实，我看json没加密我以为它都没加密。。。。
要不你交个pr修一下。。。
