### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by RMBDRAGON** [ihopenot/LpkUnpacker#2]
![image](https://user-images.githubusercontent.com/115329559/209134288-7c27525f-f6f7-4b0f-975f-30ad2baa9332.png)
按照usage输入出现下图情况，请问这个是我输入有问题还是我python出问题了，会报错啊，我是在LpkUnpacker.py的那个目录下直接cmd然后输入的.

**Comment by ihopenot** [comment]
缺filetype这个库，试下`python -m pip install filetype`

**Comment by RMBDRAGON** [comment]
![image](https://user-images.githubusercontent.com/115329559/209138021-d7cbca8b-43f3-4462-8640-953a22d035e7.png)
库装好了，但是似乎编码出问题了？（

**Comment by ihopenot** [comment]
看起来解密失败了，你把lpk和config都发一个上来

**Comment by RMBDRAGON** [comment]
[1.zip](https://github.com/ihopenot/LpkUnpacker/files/10287028/1.zip)
里面是lpk和config
