### ISSUE TITLE
为什么解密出来的数据不完整

### ISSUE THREAD

**Issue by mijuku233** [ihopenot/LpkUnpacker#5]
非常感谢大佬制作的工具，我在使用时碰到一点问题。
一个30m的lpk文件解密出来只有18m，缺失了近一半数据，是怎么回事？

我输入的命令：
python LpkUnpacker.py -c .\L2dFile\config.json .\L2dFile\2841455416.lpk .\Export

**Comment by mijuku233** [comment]
我所解密的文件 链接：

链接: https://pan.baidu.com/s/1SQNnAPaeT0f8n19XKDGAXQ?pwd=3yfj 提取码: 3yfj

**Comment by 2088722861** [comment]
我加了您的云盘

**Comment by mijuku233** [comment]
> 请问你是怎么运行成功这个程序的，方便教一下吗，看不懂文件应该放在哪里

安装python，打开powershell，cd 路径至lpkunpacker程序目录下，首次运行需输入 python -m pip install -r requirements.txt 安装依赖。提取lpk的命令为：python LpkUnpacker.py [-c config.json文件路径] [lpk文件路径] [输出路径]

**Comment by 2088722861** [comment]
谢谢了，晚上下班试试去

**Comment by 2088722861** [comment]
大佬方便截个图吗，或者演示视频

**Comment by mijuku233** [comment]
> 大佬方便截个图吗，或者演示视频

按 Win+R 输入 PowerShell 运行，接着在powershell里输入：

cd [此文件夹路径]

-示范：

cd C:\Users\Mijuku\Desktop\LpkUnpacker

首次运行需安装依赖，输入：

python -m pip install -r requirements.txt

回车

-提取lpk的命令：

python LpkUnpacker.py [-c config.json文件路径] [lpk文件路径] [输出路径]

-示范：

python LpkUnpacker.py -c C:\Users\Mijuku\Desktop\LPK\config.json C:\Users\Mijuku\Desktop\LPK\2880450213.lpk C:\Users\Mijuku\Desktop\LPK\EX

**Comment by 2088722861** [comment]
![16875320741554759925650244859736](https://github.com/ihopenot/LpkUnpacker/assets/133736648/90ea8e40-35c0-40b5-b1a2-9c58aaaee1b6)
大佬这是什么意思啊，是没安装成功吗

**Comment by 2088722861** [comment]
成功了，谢谢大佬啊，这个问题困扰我好久了，终于可以愉快的改图了

**Comment by kst1234567** [comment]
大佬为啥我运行不了

**Comment by nimiaoge** [comment]
> 大佬为啥我运行不了

确定你是在powershell里进了文件夹，并且安装了依赖

**Comment by bumian1230** [comment]
> > 大佬为啥我运行不了
> 
> 确定你是在powershell里进了文件夹，并且安装了依赖

大佬怎么安装依赖呢？在输了python -m pip install -r requirements.txt后一点反应也没有

**Comment by kang1237485** [comment]
> 成功了，谢谢大佬啊，这个问题困扰我好久了，终于可以愉快的改图了

你好，我看你成功了但我第一步输入文件夹路径都没反应 能教一下吗

**Comment by nimiaoge** [comment]
> > > 大佬为啥我运行不了
> > 
> > 
> > 确定你是在powershell里进了文件夹，并且安装了依赖
> 
> 大佬怎么安装依赖呢？在输了python -m pip install -r requirements.txt后一点反应也没有

先把requirements.txt下载下来，然后在文件夹目录下输入指令
