### ISSUE TITLE
那么问题来了

### ISSUE THREAD

**Issue by liu9262575** [ihopenot/LpkUnpacker#6]
我该如何把moc文件里的数据提取出来呢？我想提取moc里的模型数据来在其他软件里进行重现。例如将其变为spine的json模型数据，将其变为spine模型。

**Comment by ihopenot** [comment]
这个工具干不了这事，你可能需要[这个项目](https://github.com/UlyssesWu/D2Evil)

**Comment by liu9262575** [comment]
> 这个工具干不了这事，你可能需要[这个项目](https://github.com/UlyssesWu/D2Evil)

感谢指路，我去看看。
