### ISSUE TITLE
Issue：如何使用这个项目，并没有弹出控制台供我选择

### ISSUE THREAD

**Issue by CodeEngieer** [ihopenot/LpkUnpacker#7]
这是在Pycharm运行的效果，![image](https://github.com/ihopenot/LpkUnpacker/assets/75971727/b99ac933-ae45-4356-bdb5-3f1297158277)

**Comment by ihopenot** [comment]
缺少启动参数
```
python LpkUnpacker.py TARGET.lpk OUTPUT
```
把TARGET替换成你的lpk名字
OUTPUT替换成你用来存放输出结果的文件夹

**Comment by ihopenot** [comment]
Duplicate of #8
